name: alphafold3_env
channels:
  - defaults
  - conda-forge
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=4.5
  - annotated-types=0.7.0
  - biopython=1.85
  - blas=1.0
  - bottleneck=1.4.2
  - brotli=1.1.0
  - brotli-bin=1.1.0
  - bzip2=1.0.8
  - ca-certificates=2025.1.31
  - contourpy=1.3.1
  - cycler=0.12.1
  - fonttools=4.55.4
  - freetype=2.12.1
  - kiwisolver=1.4.7
  - lcms2=2.16
  - ld_impl_linux-64=2.40
  - lerc=4.0.0
  - libblas=3.9.0
  - libbrotlicommon=1.1.0
  - libbrotlidec=1.1.0
  - libbrotlienc=1.1.0
  - libcblas=3.9.0
  - libdeflate=1.20
  - libffi=3.4.4
  - libgcc=14.2.0
  - libgcc-ng=14.2.0
  - libgfortran=14.2.0
  - libgfortran-ng=14.2.0
  - libgfortran5=14.2.0
  - libgomp=14.2.0
  - libjpeg-turbo=3.0.0
  - liblapack=3.9.0
  - libopenblas=0.3.28
  - libpng=1.6.43
  - libstdcxx=14.2.0
  - libstdcxx-ng=14.2.0
  - libtiff=4.6.0
  - libuuid=1.41.5
  - libwebp-base=1.5.0
  - libxcb=1.15
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib-base=3.10.0
  - munkres=1.1.4
  - ncurses=6.4
  - numexpr=2.10.1
  - openjpeg=2.5.2
  - openssl=3.4.0
  - packaging=24.2
  - pandas=2.2.3
  - patsy=1.0.1
  - pip=24.2
  - polars=1.20.0
  - pthread-stubs=0.4
  - pydantic=2.10.2
  - pydantic-core=2.27.1
  - pyparsing=3.2.1
  - python=3.11.10
  - python-dateutil=2.9.0.post0
  - python-tzdata=2025.1
  - python_abi=3.11
  - pytz=2024.1
  - pyyaml=6.0.2
  - qhull=2020.2
  - readline=8.2
  - seaborn=0.13.2
  - seaborn-base=0.13.2
  - setuptools=75.1.0
  - six=1.17.0
  - sqlite=3.45.3
  - statsmodels=0.14.4
  - tk=8.6.14
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024b
  - unicodedata2=16.0.0
  - wheel=0.44.0
  - xorg-libxau=1.0.12
  - xorg-libxdmcp=1.1.5
  - xz=5.4.6
  - yaml=0.2.5
  - zlib=1.2.13
  - zstd=1.5.6
  - pip:
      - absl-py==2.1.0
      - chex==0.1.87
      - dm-haiku==0.0.13
      - dm-tree==0.1.8
      - filelock==3.16.1
      - hmmer==3.4.0.0
      - jax==0.4.34
      - jax-cuda12-pjrt==0.4.34
      - jax-cuda12-plugin==0.4.34
      - jax-triton==0.2.0
      - jaxlib==0.4.34
      - jaxtyping==0.2.34
      - jmp==0.0.4
      - ml-dtypes==0.5.0
      - numpy==2.1.3
      - nvidia-cublas-cu12==12.6.3.3
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvcc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-nccl-cu12==2.23.4
      - nvidia-nvjitlink-cu12==12.6.77
      - opt-einsum==3.4.0
      - pillow==11.0.0
      - rdkit==2024.3.5
      - scipy==1.14.1
      - tabulate==0.9.0
      - toolz==1.0.0
      - tqdm==4.67.0
      - triton==3.1.0
      - typeguard==2.13.3
      - zstandard==0.23.0
