"""Argument groups shared by the pipeline command-line tools."""

import argparse

from ..runtime import GPU_TYPES

MOLECULE_TYPE_HELP = '"protein", "ligand_ccd", "ligand_smiles", "dna", or "rna"'


def add_stage_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--make_feature",
        help="Generate only features for the inputs.",
        action="store_true",
    )
    parser.add_argument(
        "--make_complex",
        help="Generate only complexes from existing features.",
        action="store_true",
    )
    parser.add_argument(
        "--make_both",
        help="Generate features and then complexes in one run.",
        action="store_true",
    )
    parser.add_argument(
        "--feature_path",
        help="Directory containing features generated by --make_feature.",
    )


def add_slurm_arguments(parser: argparse.ArgumentParser, default_time: int) -> None:
    parser.add_argument(
        "--destination",
        help="Directory for AlphaFold inputs, outputs, scripts, and Slurm logs.",
        required=True,
    )
    parser.add_argument(
        "--time", help="Minutes to allocate per job.", type=int, default=default_time
    )
    parser.add_argument("--mem", help="Memory in GB per job.", type=int, default=64)
    parser.add_argument("--mail", help="Email for job notifications.")
    parser.add_argument(
        "--gpu_type",
        help="GPU type to request.",
        choices=GPU_TYPES,
        default="a100",
    )
    parser.add_argument(
        "--max_jobs",
        help="Maximum number of Slurm array tasks; inputs are batched to fit.",
        type=int,
        default=1990,
    )
    parser.add_argument(
        "--overwrite",
        help="Replace an existing generated inputs directory before writing new inputs.",
        action="store_true",
    )


def add_check_arguments(parser: argparse.ArgumentParser) -> None:
    parser.add_argument(
        "--check_only",
        help="Check for completed outputs only; do not submit jobs.",
        action="store_true",
    )
    parser.add_argument(
        "--check_only_exact",
        help=(
            "Print detailed failure information from Slurm logs and delete the "
            "output directories of failed predictions so they can be re-run."
        ),
        action="store_true",
    )
    parser.add_argument(
        "--check_stat",
        help="Write pLDDT, ipTM, and pTM statistics for completed jobs.",
        action="store_true",
    )


def resolve_job_type(args: argparse.Namespace) -> str:
    """Validate the stage flags and return the wrapper job type."""
    if args.make_feature + args.make_complex + args.make_both != 1:
        raise SystemExit(
            "Exactly one of --make_feature, --make_complex, or --make_both must be provided."
        )
    if args.feature_path is not None and not args.make_complex:
        raise SystemExit("--feature_path can only be used with --make_complex.")
    if args.make_feature:
        return "make_feature"
    if args.make_complex:
        return "make_complex"
    return "both"
